In [3]:
import numpy
print("Hello World")

Hello World


In [8]:
import numpy
vector = numpy.array([5,6,8,0,1])
metrix = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(vector)
print(metrix)


[5 6 8 0 1]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
vector = numpy.array([1,2,3,4,5,6,7])
print(vector.shape)

(7,)


In [11]:
vector == 5

array([False, False, False, False,  True, False, False])

In [13]:
import numpy as up
print(up.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
a= up.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
a = up.array([1,2,3])
b = up.arange(3)
print(a)
print(b)
c = a - b
print(c)


[1 2 3]
[0 1 2]
[1 1 1]


In [1]:
print("hello 天朝")

hello 天朝


In [3]:
import graphviz

ModuleNotFoundError: No module named 'graphviz'